#!/usr/bin/env python3
"""Weekly Report Generator for J.A.R.V.I.S - Master Mehdi"""
import json
import os
from datetime import datetime, timedelta
from pathlib import Path

def generate_weekly_report(parameters: dict = None, response=None, player=None, session_memory=None) -> str:
    """Generate weekly productivity and system report."""
    now   = datetime.now()
    week  = now.strftime("Week %W, %Y")
    start = (now - timedelta(days=7)).strftime("%Y-%m-%d")
    end   = now.strftime("%Y-%m-%d")
    
    logs_dir = Path(__file__).resolve().parent.parent / "logs"
    
    total_msgs = 0
    daily_counts = {}
    
    try:
        for log_file in sorted(logs_dir.glob("conversation_*.json")):
            date_str = log_file.stem.replace("conversation_", "")
            if date_str >= start:
                try:
                    data = json.loads(log_file.read_text(encoding="utf-8"))
                    count = len(data)
                    total_msgs += count
                    daily_counts[date_str] = count
                except:
                    pass
    except:
        pass
    
    # Memory stats
    mem_path = Path(__file__).resolve().parent.parent / "memory" / "long_term.json"
    mem_facts = 0
    try:
        mem = json.loads(mem_path.read_text(encoding="utf-8"))
        for cat in mem.values():
            if isinstance(cat, dict):
                mem_facts += len(cat)
    except:
        pass
    
    lines = [
        "=" * 50,
        f"J.A.R.V.I.S WEEKLY REPORT — {week}",
        f"For: Master Mehdi Barchichou",
        f"Period: {start} to {end}",
        "=" * 50,
        "",
        "📊 Activity Summary:",
        f"  Total conversations: {total_msgs}",
        f"  Memory facts stored: {mem_facts}",
        "",
        "📅 Daily Activity:",
    ]
    
    for date, count in sorted(daily_counts.items()):
        bar = "█" * min(count, 20)
        lines.append(f"  {date}: {bar} ({count})")
    
    # System health
    try:
        import psutil
        lines.extend([
            "",
            "💻 System Health:",
            f"  CPU Usage: {psutil.cpu_percent(interval=0.5)}%",
            f"  RAM Usage: {psutil.virtual_memory().percent}%",
            f"  Disk Usage: {psutil.disk_usage('/').percent}%",
            f"  Uptime: {int((datetime.now().timestamp() - psutil.boot_time()) / 3600)} hours",
        ])
    except:
        pass
    
    lines.extend([
        "",
        "=" * 50,
        "Report generated by J.A.R.V.I.S",
        "Enhanced by Mehdi Barchichou",
    ])
    
    report = "\n".join(lines)
    
    # Save report
    report_dir = Path.home() / "Documents" / "JARVIS_Reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_file = report_dir / f"weekly_report_{now.strftime('%Y_%W')}.txt"
    report_file.write_text(report)
    
    return report + f"\n\nSaved to: {report_file}"
